name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: |
        POD_IP=`hostname -i`
        echo "The Pod IP running this action is ${POD_IP}"
        echo "The Node IP running this action is ${NODE_IP}"
    - run: echo "🎉 This job uses runner scale set runners!"
